### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by TheSamDev** [lukas9812/FileWriter#1]
Hi, we want to use this application on project but there's no guide on how to use this locally.

We have a huge amount of large files (can't share due to NDA) that we need to split into several chunks and this tool looks like it could do the job. But we cannot found any guide how to use it.
Can you provide a guide please ?

**Comment by lukas9812** [comment]
Hello Sam, yes sure, I also use this approach on real project for my German customer. Also I can create NuGet package from it, but do not exactly when.
If you need it asap, just do a basic copy of needed service and use it as basic reference :-)

**Comment by lukas9812** [comment]
Hello @TheSamDev , I currently created a [NuGet](https://github.com/users/lukas9812/packages/nuget/package/RollingFileWriter) package for FileWriter.
Please take a look to the [README](https://github.com/lukas9812/FileWriter/blob/main/README.md) before using.

**Comment by lukas9812** [comment]
Hello @TheSamDev, the package was set to visibility "private", so I changed to public. Can you please check ?

**Comment by lukas9812** [comment]
Hello @SedlarDavid, have you please ever solve this error ? 
The package is set everywhere to "public" and I cannot find it under https://www.nuget.org even I have it setup in my nuget.config  as a source:
```
<packageSources>
        <add key="github" value="https://nuget.pkg.github.com/lukas9812/index.json" />
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
</packageSources>
```

**Comment by SedlarDavid** [comment]
> Hello @SedlarDavid, have you please ever solve this error ? The package is set everywhere to "public" and I cannot find it under https://www.nuget.org even I have it setup in my nuget.config as a source:
> 
> ```
> <packageSources>
>         <add key="github" value="https://nuget.pkg.github.com/lukas9812/index.json" />
>         <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
> </packageSources>
> ```

Hey @lukas9812 !
I believe that your issue is that the package is **NOT** available inside nuget.org, but instead, you did publish it on Github under Nuget packages. You can see that clearly in your provided code, in the URL 'nuget.pkg.github.com'. 
Additionally, I tried resolving this error locally by adding a Github Nuget feed into my test app to download your Nuget but I was unable to do that. I think there might be an issue with some sort of authentication of your package on Github, and other developers (Sam or Me) are unable to log in to your Nuget workspace and download it. 
I suggest taking a look at [this documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry) and there might be steps on how to alter your nuget download verification.

**Comment by lukas9812** [comment]
I want to thank you @SedlarDavid, I knew you help me!
I did not realize nuget.org and Github Packages are 2 different providers.
Anyway @TheSamDev, now the package is published within https://www.nuget.org/packages/RollingFileWriter.
If there would be some bugs, please create a new Issue :-)

**Comment by lukas9812** [comment]
Hello @TheSamDev,
I guess you're using the newly created method void WriteData(object dataAsObject) and pasting List<T> inside as incoming parameter. 
It's obviously a BUG, because there should be some additional serialization of the collection to string and its value string will be written to file.

**Comment by lukas9812** [comment]
@TheSamDev 
Already did a bugfix and the newest version version is 1.2.2: https://www.nuget.org/packages/RollingFileWriter/
Also I test it and everything seems to be fine:
![image](https://github.com/user-attachments/assets/88a9deb0-c971-4c7c-9fdc-41b5e95f3673)
